/// <summary>
/// 
/// __author__ = "sun hai lang"
/// __date__ 2019-07-17
/// 
/// </summary>

using MySql.Data.MySqlClient;
using SoftLiu_VSMainMenuTools.Singleton;
using System;
using System.Data;
using System.Data.SqlClient;
using System.Windows.Forms;

namespace SoftLiu_VSMainMenuTools.Utils.DatabaseManager
{
    public class MysqlManager : AutoGeneratedSingleton<MysqlManager>
    {
        private string m_connectString = null;
        public MysqlManager()
        {
            if (string.IsNullOrEmpty(m_connectString))
            {
                m_connectString = ConfigurationUtils.Instance.GetConnectionSettingValue("mySql");
            }
        }

        public DataSet SelectTables(string query)
        {
            using (MySqlConnection connection = new MySqlConnection(m_connectString))
            {
                DataSet ds = new DataSet();
                try
                {
                    connection.Open();
                    MySqlDataAdapter command = new MySqlDataAdapter(query, connection);
                    command.Fill(ds);
                }
                catch (System.Data.SqlClient.SqlException ex)
                {
                    throw new Exception(ex.Message);
                }
                finally
                {
                    connection.Close();
                }
                return ds;
            }
        }

        public bool ExistsData(string tableName, string conditions)
        {
            string query = string.Format("select count(*) from {0} where {1} limit 1;", tableName, conditions);
            int result = 0;
            using (MySqlConnection connection = new MySqlConnection(m_connectString))
            {
                try
                {
                    connection.Open();
                    MySqlCommand mycmd1 = new MySqlCommand(query, connection);
                    object obj = mycmd1.ExecuteScalar();
                    if (obj != null)
                    {
                        result = Convert.ToInt32(obj);
                    }
                }
                catch (System.Data.SqlClient.SqlException msg)
                {
                    MessageBox.Show(string.Format("Mysql ExistsData Error: {0}", msg.Message), "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
                finally
                {
                    connection.Close();
                }
                if (result > 0)
                {
                    return true;
                }
                return false;
            }
        }
        /// <summary>
        /// 插入数据 表示全列插入
        /// </summary>
        /// <param name="tableName">表名</param>
        /// <param name="sqlData">插入的数据</param>
        /// <returns></returns>
        public int InsesetData(string tableName, string sqlData)
        {
            if (string.IsNullOrEmpty(sqlData)) return 0;
            string query = string.Format("insert into {0} values({1});", tableName, sqlData);
            int result = 0;
            using (MySqlConnection connection = new MySqlConnection(m_connectString))
            {
                try
                {
                    connection.Open();
                    MySqlCommand mycmd1 = new MySqlCommand(query, connection);
                    result = mycmd1.ExecuteNonQuery();
                }
                catch (SqlException msg)
                {
                    MessageBox.Show(string.Format("Mysql InsesetData Error: {0}", msg.Message), "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
                finally
                {
                    connection.Close();
                }
                return result;
            }
        }

        public int UpdateData(string query)
        {
            if (string.IsNullOrEmpty(query)) return 0;

            int result = 0;
            using (MySqlConnection connection = new MySqlConnection(m_connectString))
            {
                try
                {
                    connection.Open();
                    MySqlCommand mycmd1 = new MySqlCommand(query, connection);
                    result = mycmd1.ExecuteNonQuery();
                }
                catch (SqlException msg)
                {
                    MessageBox.Show(string.Format("Mysql UpdateData Error: {0}", msg.Message), "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
                finally
                {
                    connection.Close();
                }
                return result;
            }
        }

        public int DeleteData(string query)
        {
            if (string.IsNullOrEmpty(query)) return 0;
            int result = 0;
            using (MySqlConnection connection = new MySqlConnection(m_connectString))
            {
                try
                {
                    connection.Open();
                    MySqlCommand mycmd1 = new MySqlCommand(query, connection);
                    result = mycmd1.ExecuteNonQuery();
                }
                catch (SqlException msg)
                {
                    MessageBox.Show(string.Format("Mysql DeleteData Error: {0}", msg.Message), "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
                finally
                {
                    connection.Close();
                }
                return result;
            }
        }

        ~MysqlManager()
        {

        }
    }
}
