/// <summary>
/// 
/// __author__ = "sun hai lang"
/// __date__ 2019-07-17
/// 
/// </summary>

using MySql.Data.MySqlClient;
using SoftLiu_VSMainMenuTools.Singleton;
using System;
using System.Data;

namespace SoftLiu_VSMainMenuTools.Utils.DatabaseManager
{
    public class MysqlManager : AutoGeneratedSingleton<MysqlManager>
    {
        private string m_connectString = null;
        public MysqlManager()
        {
            if (string.IsNullOrEmpty(m_connectString))
            {
                m_connectString = ConfigurationUtils.Instance.GetConnectionSettingValue("mySql");
            }            
        }

        public DataSet SelectTables(string query)
        {
            using (MySqlConnection connection = new MySqlConnection(m_connectString))
            {
                DataSet ds = new DataSet();
                try
                {
                    connection.Open();
                    MySqlDataAdapter command = new MySqlDataAdapter(query, connection);
                    command.Fill(ds);
                }
                catch (System.Data.SqlClient.SqlException ex)
                {
                    throw new Exception(ex.Message);
                }
                finally
                {
                    connection.Close();
                }
                return ds;
            }
        }

        public int InsesetData(string query)
        {            
            if (string.IsNullOrEmpty(query)) return 0;

            int result = 0;
            using (MySqlConnection connection = new MySqlConnection(m_connectString))
            {
                try
                {
                    connection.Open();
                    MySqlCommand mycmd1 = new MySqlCommand(query, connection);
                    result = mycmd1.ExecuteNonQuery();
                }
                catch (System.Data.SqlClient.SqlException ex)
                {
                    throw new Exception(ex.Message);
                }
                finally
                {
                    connection.Close();
                }
                return result;
            }
        }

        public int DeleteData(string query)
        {
            if (string.IsNullOrEmpty(query)) return 0;
            int result = 0;
            using (MySqlConnection connection = new MySqlConnection(m_connectString))
            {
                try
                {
                    connection.Open();
                    MySqlCommand mycmd1 = new MySqlCommand(query, connection);
                    result = mycmd1.ExecuteNonQuery();
                }
                catch (System.Data.SqlClient.SqlException ex)
                {
                    throw new Exception(ex.Message);
                }
                finally
                {
                    connection.Close();
                }
                return result;
            }
        }

        ~MysqlManager()
        {

        }
    }
}
