using MySql.Data.MySqlClient;
using SoftLiu_VSMainMenuTools.Singleton;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SoftLiu_VSMainMenuTools.Utils.DatabaseManager
{
    public class MysqlManager : AutoGeneratedSingleton<MysqlManager>
    {
        private string m_connectString = null;
        public MysqlManager()
        {
            if (string.IsNullOrEmpty(m_connectString))
            {
                m_connectString = ConfigurationUtils.Instance.GetConnectionSettingValue("mySql");
            }            
        }

        public MySqlDataReader SelectTables(string query)
        {
            MySqlConnection myConnection = new MySqlConnection(m_connectString);
            MySqlCommand myCommand = new MySqlCommand(query, myConnection);
            myConnection.Open();
            myCommand.ExecuteNonQuery();
            MySqlDataReader myDataReader = myCommand.ExecuteReader();
            myDataReader.Close();
            myConnection.Close();

            return myDataReader;
        }

        ~MysqlManager()
        {

        }
    }
}
