/// <summary>
/// 
/// __author__ = "sun hai lang"
/// __date__ 2019-07-16
/// 
/// </summary>

namespace SoftLiu_VSMainMenuTools.Singleton
{
    public class AutoGeneratedSingleton<T> where T : AutoGeneratedSingleton<T>, new()
    {
        private static T m_instance = null;
        private static object _lock = new object();

        public static T Instance
        {
            get
            {
                lock (_lock)
                {
                    if (m_instance == null)
                    {
                        m_instance = new T();
                    }

                    return m_instance;
                }
            }
        }
    }
}
