//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TConfiger {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CSharpTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CSharpTemplate() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TConfiger.CSharpTemplate", typeof(CSharpTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ///Auto-generated file, do not modify
        ///
        ///namespace __namespace__
        ///{
        ///    public enum __className__ : int
        ///    {
        ///__fields__
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string EnumTemplate {
            get {
                return ResourceManager.GetString("EnumTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ///Auto-generated file, do not modify
        ///
        ///using System.Runtime.InteropServices;
        ///
        ///namespace __namespace__
        ///{
        ///    public unsafe partial struct __className__ : IConfigType
        ///    {
        ///        [StructLayout(LayoutKind.Sequential)]
        ///        private unsafe struct __dataName__
        ///        {
        ///__dataFields__
        ///        }
        ///
        ///        private static byte* dataPointer { get { Table.TableIndexCheck(TableIndex.__className__); return Table.GetDataPointer(TableIndex.__className__); } }
        ///        public static int Count { get { Tabl [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string InstanceTemplate {
            get {
                return ResourceManager.GetString("InstanceTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ///Auto-generated file, do not modify
        ///
        ///using System.Runtime.InteropServices;
        ///
        ///namespace __namespace__
        ///{
        ///    public static unsafe partial class __className__
        ///    {
        ///        [StructLayout(LayoutKind.Sequential)]
        ///        private unsafe struct __dataName__
        ///        {
        ///__dataFields__
        ///        }
        ///
        ///        private static byte* dataPointer { get { return Table.GetDataPointer(TableIndex.__className__); } }
        ///        private static __dataName__* p { get { return (__dataName__*)Table.ConfigByIndex(TableIndex._ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string StaticTemplate {
            get {
                return ResourceManager.GetString("StaticTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ///Auto-generated file, do not modify
        ///
        ///using System.Runtime.InteropServices;
        ///
        ///namespace __namespace__
        ///{
        ///    public unsafe partial struct __className__ : IConfigStruct
        ///    {
        ///        [StructLayout(LayoutKind.Sequential)]
        ///        private struct __dataName__
        ///        {
        ///__dataFields__
        ///        }
        ///
        ///        public void SetPointer(byte* p, byte* dataPointer, int pVersion) { this.p = (__dataName__*)p; this.dataPointer = dataPointer; this.pVersion = pVersion; }
        ///        public __className__(byte* p, byte*  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string StructTemplate {
            get {
                return ResourceManager.GetString("StructTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ///Auto-generated file, do not modify
        ///
        ///using Framework;
        ///
        ///namespace __namespace__
        ///{
        ///    public unsafe partial class __className__
        ///    {
        ///__fields__
        ///
        ///        public static void SetData()
        ///        {
        ///__setDataContents__
        ///        }
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string TableIndex {
            get {
                return ResourceManager.GetString("TableIndex", resourceCulture);
            }
        }
    }
}
