//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelTConfig {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PythonTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PythonTemplate() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelTConfig.PythonTemplate", typeof(PythonTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 #!/usr/bin/env python3
        ///#coding=utf-8
        ///
        ///#importContent
        ///
        ///class Config:
        ///
        ///    @staticmethod
        ///    def loadAll():
        ///        __loadContent__ 的本地化字符串。
        /// </summary>
        internal static string EntryTemplate {
            get {
                return ResourceManager.GetString("EntryTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #!/usr/bin/env python3
        ///#coding=utf-8
        ///
        ///from enum import IntEnum
        ///
        ///class EnumName(IntEnum):
        ///    __fields__ 的本地化字符串。
        /// </summary>
        internal static string EnumTemplate {
            get {
                return ResourceManager.GetString("EnumTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #!/usr/bin/env python3
        ///#coding=utf-8
        ///
        ///from .ConfigTool import ConfigTool
        ///from typing import TypeVar, Dict, Tuple
        ///
        ///class __KlassName__:
        ///
        ///    __slots__ = (__slotsContent__)
        ///    count = 0 #type: int
        ///    configs = None #type: Tuple[__KlassName__]
        ///    idConfigsMap = None #type: Dict[int, __KlassName__]
        ///    #{codeName}nameConfigsMap = None #type: Dict[str, __KlassName__]
        ///
        ///    def __init__(self, data):
        ///        __initContent__
        ///
        ///    @classmethod
        ///    def load(cls):
        ///        if cls.configs: return
        ///  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Instance {
            get {
                return ResourceManager.GetString("Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #!/usr/bin/env python3
        ///#coding=utf-8
        ///
        ///#{import}from .ConfigTool import ConfigTool
        ///from typing import List
        ///
        ///class __StructName__:
        ///
        ///    __slots__ = (__slotsContent__)
        ///
        ///    def __init__(self, data):
        ///        #{import}__importContent__
        ///        __initContent__ 的本地化字符串。
        /// </summary>
        internal static string StructTemplate {
            get {
                return ResourceManager.GetString("StructTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #!/usr/bin/env python3
        ///#coding=utf-8
        ///
        ///class __VName__:
        ///    __fields__ 的本地化字符串。
        /// </summary>
        internal static string VTemplate {
            get {
                return ResourceManager.GetString("VTemplate", resourceCulture);
            }
        }
    }
}
