using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SoftLiu_VSMainMenuTools.Singleton;
using System.Windows.Forms;
using System.Threading;

namespace SoftLiu_VSMainMenuTools.UGUI
{
    public class FormManager : AutoGeneratedSingleton<FormManager>
    {

        private Stack<Form> m_FormStackList = null;

        public FormManager()
        {
            m_FormStackList = new Stack<Form>();
        }

        public void OpenForm(Form form)
        {
            if (form is MainMenuForm)
            {
                m_FormStackList.Push(form);
                Thread th = new Thread(() => {
                    Application.Run(form);
                });
                th.SetApartmentState(ApartmentState.STA);
                th.Start();
                //form.Show();
            }
            else
            {
                Form perForm = m_FormStackList.Peek();
                perForm.Hide();
                m_FormStackList.Push(form);
                form.Show();
            }
        }

        public void BackClose()
        {
            if (m_FormStackList.Count > 1)
            {
                Form perForm = m_FormStackList.Pop();
                perForm.Close();
                perForm.DialogResult = DialogResult.OK;
            }
            if (m_FormStackList.Count == 1)
            {
                // main
                Form main = m_FormStackList.Peek();
                main.Show();
            }
            else
            {
                Form curForm = m_FormStackList.Peek();
                curForm.Show();
            }
        }

    }
}
