using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SoftLiu_VSMainMenuTools.Singleton;
using System.Windows.Forms;
using System.Threading;

namespace SoftLiu_VSMainMenuTools.UGUI
{
    public class FormManager : AutoGeneratedSingleton<FormManager>
    {

        private Stack<Form> m_FormStackList = null;

        public FormManager()
        {
            m_FormStackList = new Stack<Form>();
        }

        public void OpenForm(Form curForm)
        {
            if (curForm is MainMenuForm)
            {
                m_FormStackList.Push(curForm);
                Thread th = new Thread(() =>
                {
                    Application.Run(curForm);
                });
                curForm.StartPosition = FormStartPosition.CenterScreen;
                th.SetApartmentState(ApartmentState.STA);
                th.Start();                
                return;
            }
            Form perForm = m_FormStackList.Peek();
            perForm.Hide();
            m_FormStackList.Push(curForm);
            curForm.StartPosition = FormStartPosition.Manual;
            curForm.Location = perForm.Location;
            curForm.Show();
        }

        public void BackClose()
        {
            Form perForm = null;
            if (m_FormStackList.Count > 1)
            {
                perForm = m_FormStackList.Pop();
                perForm.Hide();
            }
            // set pervious form
            Form curForm = m_FormStackList.Peek();
            if (perForm != null)
            {
                curForm.Location = perForm.Location;
                // close current form
                perForm.Close();
                perForm.DialogResult = DialogResult.OK;
                perForm.Dispose();
            }
            curForm.Show();
        }
    }
}
