/// <summary>
/// 
/// __author__ = "sun hai lang"
/// __date__ 2019-07-16
/// 
/// </summary>

using SoftLiu_VSMainMenuTools.Singleton;
using System;
using System.Collections.Specialized;
using System.Configuration;

namespace SoftLiu_VSMainMenuTools.Utils
{
    class ConfigurationUtils : AutoGeneratedSingleton<ConfigurationUtils>
    {
        /// <summary>
        /// 获取当前 App.config 中 appSetting 的 key—value 值
        /// </summary>
        private NameValueCollection m_appSetting = null;

        private ConnectionStringSettingsCollection m_connectionSetting = null;

        public ConfigurationUtils()
        {
            if (m_appSetting == null)
            {
                m_appSetting = ConfigurationManager.AppSettings;
            }
            if (m_connectionSetting == null)
            {
                m_connectionSetting = ConfigurationManager.ConnectionStrings;
            }
        }
        /// <summary>
        /// 获取当前 App.config 中 appSetting 的 key—value 值
        /// </summary>
        /// <param name="key">key 值</param>
        /// <returns></returns>
        public string GetAppSettingValue(string key)
        {
            try
            {
                if (m_appSetting != null)
                {
                    return m_appSetting[key] ?? null;
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(string.Format("GetAppSettingValue Error : {0} , key:{1}", e.Message, key));
            }

            return null;
        }
        /// <summary>
        /// 获取当前 App.config 中 connectionSetting 的 key—value 值
        /// </summary>
        /// <param name="name">name 值</param>
        /// <returns></returns>
        public string GetConnectionSettingValue(string name)
        {
            try
            {
                if (m_connectionSetting != null)
                {
                    return m_connectionSetting[name].ConnectionString;
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(string.Format("GetConnectionSettingValue Error : {0} , key:{1}", e.Message, name));
            }

            return null;
        }

        ~ConfigurationUtils()
        {
            if (m_appSetting != null)
            {
                m_appSetting = null;
            }
            if (m_connectionSetting != null)
            {
                m_connectionSetting = null;
            }
        }


    }
}
