using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using SoftLiu_VSMainMenuTools.Singleton;

namespace SoftLiu_VSMainMenuTools.Utils
{
    public class ThreadPoolManager : AutoGeneratedSingleton<ThreadPoolManager>
    {

        public ThreadPoolManager()
        {
            //ThreadPool.SetMinThreads(2, 5);
            ThreadPool.SetMaxThreads(10, 10);
        }

        public void QueueUserWorkItem(WaitCallback callback)
        {
            ThreadPool.QueueUserWorkItem(callback);
        }

    }
}
