/// <summary>
/// 
/// __author__ = "sun hai lang"
/// __date__ 2019-07-16
/// 
/// </summary>

using SoftLiu_VSMainMenuTools.Singleton;
using SoftLiu_VSMainMenuTools.Utils.EventsManager;
using System;

namespace SoftLiu_VSMainMenuTools.Utils
{
    public sealed class VersionUtils : AutoGeneratedSingleton<VersionUtils>
    {
        /// <summary>
        /// 获取当前程序的版本号
        /// </summary>
        public Version version
        {
            private set;
            get;
        }

        public int versionCode
        {
            private set;
            get;
        }

        public VersionUtils()
        {
            Update();
            EventManager<Events>.Instance.RegisterEvent(Events.UpdateVersionEvent, OnUpdateVersionEvent);

        }

        private void Update()
        {
            string ver = ConfigurationUtils.Instance.GetAppSettingValue("versionName");
            version = new Version(ver);
            string code = ConfigurationUtils.Instance.GetAppSettingValue("versionCode");
            int result = 0;
            int.TryParse(code, out result);
            versionCode = result;
        }

        private void OnUpdateVersionEvent(Events eventType, object[] arg2)
        {
            Update();
            EventManager<Events>.Instance.TriggerEvent(Events.UpdateVersionCompleteEvent, null);
        }

        ~VersionUtils()
        {
            if (version != null)
                version = null;
            versionCode = 0;

            EventManager<Events>.Instance.DeregisterEvent(Events.UpdateVersionEvent, OnUpdateVersionEvent);
        }

    }
}
